//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResitSchedule
    {
        public int ResitScheduleID { get; set; }
        public int DebtID { get; set; }
        public System.DateTime ScheduledDate { get; set; }
        public Nullable<int> ClassroomID { get; set; }
        public int AttemptNumber { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual Debt Debt { get; set; }
    }
}
