//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleID { get; set; }
        public int DebtID { get; set; }
        public System.DateTime ExamDate { get; set; }
        public int TimeSlot { get; set; }
        public int ClassroomID { get; set; }
        public int TimeSlotID { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual Debt Debt { get; set; }
        public virtual TimeSlot TimeSlot1 { get; set; }
    }
}
